version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-learning
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - './queue/data:/var/lib/rabbitmq'
      - './queue/log:/var/log/rabbitmq'
  nodejs-app:
    image: node:20.7.0-alpine3.17
    container_name: my-nodejs-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: tail -f /dev/null
    links:
      - rabbitmq